spring:
  application:
    name: sass-admin
  profiles:
    include:
      - postgresql
  data:
    redis:
      password: ENC(e6iMIrKwnRc8PSiAY9jaCDuGf5CGiMcpC35GBtvKVrGjSjkgQFfKJxiu3rEeAE1s)
      host: ENC(J35ERjUJ4z8f5dWg/dK4Li4mhBpoVwxu4jZLLcpi4nEkPoOD0g4iCKar5KLZIRGQ)
      port: 16379
base:
  framework:
    cache:
      service:
        cache-service-type: redis
    kms-national:
      sm2:
        auto-generate: true
    database:
      transaction-expression: execution(* com.fuhouyu.sass.platform.system..service.*Service.*(..))
mybatis:
  mapper-locations: classpath*:mapper/*.xml