spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(h68wJyu6X3ZHLJqUYalNHbQqeGFlOz5vBeVWH1suZdhQxl7LDd4HJFhN2AOIwMyEtbxoZM9+Nsn7WhZhWA4Yk+OvYgmlOVvX2z9knRdn88d0hPA2XS/TS6t6FXuXbSsyz5J4VZ3w/zKHazVWQvzreP3NDigV1z1cNKgAjs5kQMU=)
    username: ENC(vvYG+yd7uhdG+nHjmony1jXyq5iBwSCKteYmXSc0KbKm8JNMQ04DsqHougMTnlyy)
    password: ENC(xZ2Wj+sKHpJsl2AnKm2klATW28QaI12vG3Tv5uxJSeBY4g1mlkg9t5dTRjKfDw0c)
    type: com.alibaba.druid.pool.DruidDataSource