spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(aG+vcXvSuJp2t3utf9bOJFPkQGTwu6odQEArFJ2rCFU9woDE34onQHrgrZxf32VU3Hm5e8ztA38eN+DP9iYDIG57cjTVKp5VM9O+LfTeJoL22Eaia4eGHKL/9fK6R1U1)
    username: ENC(2Uo9eOpR9V28U24F/9XfDHnCaG+t2lPaPUk04XFBUmi9/55WPDg2PJaBUrDMNnKU)
    password: ENC(nwT7w8xRFdJku4Q0ikY0xTEeeIFresONmyhjZ0qFVw0jBRNuda+U92Zd5bw/bvT6)
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      password: ENC(e6iMIrKwnRc8PSiAY9jaCDuGf5CGiMcpC35GBtvKVrGjSjkgQFfKJxiu3rEeAE1s)
      host: ENC(J35ERjUJ4z8f5dWg/dK4Li4mhBpoVwxu4jZLLcpi4nEkPoOD0g4iCKar5KLZIRGQ)
      port: 16379
      lettuce:
        pool:
          max-idle: 30
          max-active: 8
          max-wait: 10000
          min-idle: 10
base:
  framework:
    cache:
      service:
        cache-service-type: redis
    s3:
      access-key-id: ENC(1jUCodj9k/b9P/oosIKuL3BiKVPgIVHSsl/Ina5bg+k6BXzte1LrNymYTTbs9zWI)
      secret-key: ENC(DkqIcMbrpHHiFmOh5iqfJaMFneHZ7KAUQ9mZJFAJ36O0j0dSmuPiNauBud6dPdh4)
      endpoint: ENC(hdlw+8cG79Oh9XQbDi7S7FPfVnQITyFV96WPFgDh4XRs1M6LfN8wAfS1UZbH0TcwIoAlUCTrQfPxLqRjl0teng==)
      path-style-enabled: true
    s3s3:
      sts:
        duration-seconds: 3600

sass:
  platform:
    cloudflare:
      turnstile:
        enabled: false
        url: https://challenges.cloudflare.com/turnstile/v0/siteverify
        secret: ENC(F80/1heErz1mt0hWdMctVSJxKaECnxYvewCQgNqlzLmUSl9jJF0+UOwPga8xph3VIy6Y2xtuOVkdv/glhLHXyY8YPOF10zmL4U6BQuP9qtc=)