spring:
  application:
    name: sass-admin
  profiles:
    include:
      - postgresql
  data:
    redis:
      password: ENC(ptfFQ+R/E+A+0cBOV4Yo4V0gna5DP3a/cb1uFdMnV3s7YS71YgJQOcJkJs9QOKQb+qryB460wlpsb5+RtonFZ/yuS6tPE+LgDb5x5b2SxA4=)
      host: ENC(+B2T5HTJsU1PmufEKq6Ms3IC579/zCKfErGzBotUfLYBeEqx3eU4fQGsPFT0uMeq+MEqLgyBirPo7Sk4Y01SYflKQHYjCylKAJ5rVEMUWHpPZP54iZEiT1HPaO84YDE8)
      port: 18421
base:
  framework:
    cache:
      service:
        cache-service-type: redis
    kms-national:
      sm2:
        auto-generate: true
    database:
      transaction-expression: execution(* com.fuhouyu.sass.platform.system..service.*Service.*(..))
mybatis:
  mapper-locations: classpath*:mapper/*.xml