spring:
  application:
    name: sass-admin
  profiles:
    include:
      - postgresql
  data:
    redis:
      password: wfyrgqgyy
      database: 1
      host: ENC(UUHNPvtHpEfFl+zqZBXI1HXZ26zpQ6c0ZHaYTq+n+BZrQ42diN7FGUDTYksIS8NN)
      port: 6379
      connect-timeout: 6s
base:
  framework:
    cache:
      service:
        cache-service-type: redis
    kms-national:
      sm2:
        auto-generate: true
    database:
      transaction-expression: execution(* com.fuhouyu.sass.platform.system..service.*Service.*(..))
mybatis:
  mapper-locations: classpath*:mapper/*.xml