name: java-deploy
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - feature/v1.0.0
permissions: read-all

jobs:
  public-java:
    runs-on: ubuntu-latest
    steps:
      - name: "Set up JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: "Cache Maven Repos"
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checkout base framework repository
        uses: actions/checkout@v4
        with:
          repository: fuhouyu/base-framework.git
          path: base-framework
          ref: develop

      # Step 3: Build and install the dependency
      - name: Build and install base framework dependency
        run: |
          cd base-framework
          mvn clean install -DskipTests

      - uses: actions/checkout@v4
        name: Checkout Sass Platform repository
        with:
          fetch-depth: 0
      - name: Build with Maven
        run: |
          mvn clean package -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -DskipTests -Pprod
          mv sass-platform-admin/target/sass-platform-admin-*.jar sass-platform-admin.jar
      - name: Scp Jar File
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "sass-platform-admin.jar"
          target: "/develop/projects/web"

      - name: start sass-platform-admin
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sh /develop/projects/web/startup.sh