name: web-deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
permissions: read-all

jobs:
  publish-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sass Platform repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: "Cache Npm Repos"
        uses: actions/cache@v4
        with:
          path: ~/.npm/repository
          key: ${{ runner.os }}-package-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-package-

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: pnpm build
        env:
          VITE_CLOUDFLARE_SITE_KEY: '${{ secrets.CLOUDFLARE_SITE_KEY }}'
          VITE_WELINK_CLIENT_ID: ${{ secrets.WELINK_CLIENT_ID }}
          VITE_MATOMO_URL: ${{ secrets.VITE_MATOMO_URL }}
          VITE_MATOMO_SITE_ID: ${{ secrets.VITE_MATOMO_SITE_ID }}
          VITE_SERVER_URL: ${{ vars.VITE_SERVER_URL }}
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
          VITE_LOGIN_REDIRECT_URI: ${{ vars.VITE_LOGIN_REDIRECT_URI }}
        run: |
          cd sass-platform-ui
          pnpm install && pnpm run build

      - name: Scp dist File
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "sass-platform-ui/dist/"
          target: "/develop/projects/web/static"
          strip_components: 1